name: wikilanguage
channels:
  - conda-forge
  - defaults
dependencies:
  - bidict=0.19.0
  - black=19.10b0
  - graph-tool=2.29
  - ipywidgets=7.5.1
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - jupyterlab=1.2.5
  - jupyterlab_server=1.0.6
  - msgpack-python=0.6.1
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.0
  - pip=20.0.2
  - requests=2.22.0
  - scipy=1.3.2
  - tqdm=4.42.1
  - ujson=1.35
  - urllib3=1.25.8
  - zlib=1.2.11
  - pip:
    - wikitextparser==0.29.1
